### ISSUE TITLE
Still not in Boost release?

### ISSUE THREAD

**Issue by bc-lee** [lcaminiti/boost-contract#1]
Hi, I found that your `boost-contract` library is suitable for contract-based programming in C++ and I heared your library passed boost code-review, which is cool.

However, the code review was almost [5 years ago](http://www.boost.org/community/review_schedule.html).

Are there any plans to release this libray to boost?

**Comment by lcaminiti** [comment]
Not a commitment but... I'm planning to release this library within a year... assuming the Boost community still wants it, I'll release it in Boost. Otherwise, I'll just release it on GitHub.

In the meanwhile, you are welcome to use the library from GitHub. Master is stable. I also keep the develop pretty stable and it's got the latest and greatest API. The version of the library is the develop branch is pretty much final... all implemented and tested, just a final update to the docs now.

Docs from master with example on how to use the library (including postcondition old values and subcontracting):
https://lcaminiti.github.io/boost-contract/doc/html/index.html
